### ISSUE TITLE
Help instructions should also explain Mario mechanics.

### ISSUE THREAD

**Issue by muddymind** [headshot2017/OpenLara#43]
Unfortunately many non SM64 players are not very aware of Mario mechanics and it was painful to watch a streamer take 5min to learn how to get out of water lol.

Also the several different Mario jumps and types of attacks.

**Comment by headshot2017** [comment]
![image](https://user-images.githubusercontent.com/36455681/186992188-8a4b3252-a5fe-4a3f-b23d-95414574babd.png)
